name: waste_classifier_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0-100.2.beta

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/waste_classifier.tflite
